version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - bulletin_storage:/home/web/app/storage
  redis:
    image: "redis:alpine"

volumes:
  bulletin_storage: