version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      ENV_VARIABLE: testing1
    ports:
      - "80:80"
    volumes:
      - bulletin_storage:/home/web/app/storage

  redis:
    image: "redis:alpine"
  
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: new_database
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - UPLOAD_LIMIT=256M
    restart: always
    ports:
     - 8081:80
    volumes:
     - /sessions

volumes:
  bulletin_storage: